#ifndef MBED_MXIC_ERROR_H
#define MBED_MXIC_ERROR_H

typedef enum {
	MXST_SUCCESS,
	MXST_ERR,
	MXST_NOT_DEFINED,

	MXST_FLASH_NOT_READY,
	MXST_SEND_CMD_ERR,
	MXST_TRANS_INIT_ERR,
	MXST_BUF_NULL,
	MXST_TRANS_DEINIT_ERR,
	MXST_CRC_ERR,
	MXST_ALOCATE_FAILED,
	MXST_APP_ID_ERR,

	MXST_WREN_ERR,

	MXST_ARMOR_ENSF_ERR,
	MXST_ARMOR_EXSF_ERR,
	MXST_ARMOR_SPI_WRITE_KEY_ERR,
	MXST_ARMOR_WR_SECURE_PKT_ERR,
	MXST_ARMOR_RD_SECURE_PKT_ERR,
	MXST_ARMOR_RGEN_IS_NOT_EN,
	MXST_ARMOR_OMAC_CMP_NOT_MATCH,
	MXST_ARMOR_KWR_KGEN_NOT_PERM_IN_KEYCFG,
	MXST_ARMOR_ENWR_NOT_PERM,
	MXST_ARMOR_PUFRD_NOT_PERM_IN_KEYCFG,
	MXST_ARMOR_PUFTRANS_NOT_PERM_IN_KEYCFG,
	MXST_ARMOR_MC_INCR_NOT_PERM_IN_MCCFG,
	MXST_ARMOR_ERASE_NOT_ALIGN_4K,
	MXST_ARMOR_ENCWR_NOT_ALIGN_32B,
	MXST_ARMOR_SET_KEY_METHOD_ERR,
	MXST_ARMOR_LKD_DATAZONE_NOT_PERM,
	MXST_ARMOR_LKD_FAILED,
	MXST_ARMOR_DIS_FAILED,
	MXST_ARMOR_CONFIGLKD_NOT_LOCKED,
	MXST_ARMOR_ACCESS_ADDR_EXCEEDED_ERR,
	MXST_ARMOR_AES_CCM_AUTHEN_DECRYPT_FAILED,
	MXST_ARMOR_AES_CCM_ENCRYPT_MAC_DATA_FAILED,
	MXST_ARMOR_SF_CFG_CMP_FAILED,
	MXST_ARMOR_GET_KEY_FAILED,
	MXST_ARMOR_INT_SECURE_PKT_FAILED,	

	/* ArmorFlash Error Codes */
	MXST_ARMOR_RTN_ERR_CODE_CMD,
	MXST_ARMOR_RTN_ERR_CODE_ADD,
	MXST_ARMOR_RTN_ERR_CODE_BDRY,
	MXST_ARMOR_RTN_ERR_CODE_PERM,
	MXST_ARMOR_RTN_ERR_CODE_NONCE,
	MXST_ARMOR_RTN_ERR_CODE_MAC,
	MXST_ARMOR_RTN_ERR_CODE_CNT,
	MXST_ARMOR_RTN_ERR_CODE_KEY,
	MXST_ARMOR_RTN_ERR_CODE_LKD,
	MXST_ARMOR_RTN_ERR_CODE_VFY,
	MXST_ARMOR_RTN_ERR_CODE_NOT_DEF,

}MxicStatus;

#endif
