#ifndef MBED_SECURE_FLASH_BLOCK_DEVICE_RPMC_H
#define MBED_SECURE_FLASH_BLOCK_DEVICE_RPMC_H

#define RPMC_INST1 0x9B
    #define RPMC_INST1_CMD_ROOT_KEY     0x00
    #define RPMC_INST1_CMD_HMAC_KEY     0x01
    #define RPMC_INST1_CMD_INCREMENT_MC 0x02
    #define RPMC_INST1_CMD_REQUEST_MC   0x03
#define RPMC_INST2 0x96

#define RPMC_WRITE_ROOT_KEY_IDATA_SIZE \
		(RPMC_COMMAND_SIZE + RPMC_MC_ADDRESS_SIZE + RPMC_RESERVED_SIZE + RPMC_ROOT_KEY_SIZE + RPMC_TRUNCATED_SIGNATURE_SIZE)
#define RPMC_UPDATE_HMAC_KEY_IDATA_SIZE \
		(RPMC_COMMAND_SIZE + RPMC_MC_ADDRESS_SIZE + RPMC_RESERVED_SIZE + HMAC_KEY_DATA_SIZE + RPMC_SIGNATURE_SIZE)
#define RPMC_INCREMENT_MC_IDATA_SIZE \
		(RPMC_COMMAND_SIZE + RPMC_MC_ADDRESS_SIZE + RPMC_RESERVED_SIZE + RPMC_MC_DATA_SIZE + RPMC_SIGNATURE_SIZE)
#define RPMC_REQUEST_MC_IDATA_SIZE \
		(RPMC_COMMAND_SIZE + RPMC_MC_ADDRESS_SIZE + RPMC_RESERVED_SIZE + RPMC_TAG_SIZE + RPMC_SIGNATURE_SIZE)

#define RPMC_STATUS_SUCCESS 0x80
#define RPMC_STATUS_BUSY_MASK 0x81
#define RPMC_STATUS_BUSY

#define RPMC_STATUS_WRITE_ROOT_KEY_ERROR0_MASK 0x82
#define RPMC_STATUS_WRITE_ROOT_KEY_ERROR0      0x02
#define RPMC_STATUS_WRITE_ROOT_KEY_ERROR1_MASK 0x84
#define RPMC_STATUS_WRITE_ROOT_KEY_ERROR1      0x04

#define RPMC_STATUS_UPDATE_HMAC_KEY_ERROR0_MASK 0x82
#define RPMC_STATUS_UPDATE_HMAC_KEY_ERROR0      0x02
#define RPMC_STATUS_UPDATE_HMAC_KEY_ERROR1_MASK 0x84
#define RPMC_STATUS_UPDATE_HMAC_KEY_ERROR1      0x04

#define RPMC_STATUS_INCR_MC_ERROR0_MASK 0x82
#define RPMC_STATUS_INCR_MC_ERROR0      0x02
#define RPMC_STATUS_INCR_MC_ERROR1_MASK 0x84
#define RPMC_STATUS_INCR_MC_ERROR1      0x04
#define RPMC_STATUS_INCR_MC_ERROR2_MASK 0x88
#define RPMC_STATUS_INCR_MC_ERROR2      0x08
#define RPMC_STATUS_INCR_MC_ERROR3_MASK 0x90
#define RPMC_STATUS_INCR_MC_ERROR3      0x10

#define RPMC_STATUS_REQ_MC_ERROR0_MASK 0x82
#define RPMC_STATUS_REQ_MC_ERROR0      0x02
#define RPMC_STATUS_REQ_MC_ERROR1_MASK 0x84
#define RPMC_STATUS_REQ_MC_ERROR1      0x04
#define RPMC_STATUS_REQ_MC_ERROR2_MASK 0x88
#define RPMC_STATUS_REQ_MC_ERROR2      0x08

/* basic parameter size */
#define RPMC_INST_SIZE 1
#define RPMC_COMMAND_SIZE 1
#define RPMC_MC_ADDRESS_SIZE 1
#define RPMC_RESERVED_SIZE 1
#define RPMC_KEY_SIZE 32

/* write root key parameters size */
#define RPMC_ROOT_KEY_SIZE 32
#define RPMC_TRUNCATED_SIGNATURE_SIZE 28
/* update hmac key parameter size */
#define RPMC_HMAC_KEY_DATA_SIZE 4
/* increment MC parameter size */
#define RPMC_MC_DATA_SIZE 4
/* request MC patameter size */
#define RPMC_TAG_SIZE 12

#define RPMC_SIGNATURE_SIZE 32

#endif